platform:
  - x64

environment:
  GITHUB_RELEASE_TOKEN:
    secure: ocphQJ30EXXDjy8MbCfAGZuh/gysahytkv/vuEDhEIl7s33qZemz5fmDNSJAbvUm

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

# thank you! https://github.com/chef-cookbooks/powershell/pull/113/files
init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node 8 x64
  - virtualenv venv -p C:\Python36\Python.exe
  - venv/Scripts/activate
  - where python
  - python --version
  - where pip
  - pip install -r requirements.txt
  - pip install -r requirements-tests.txt
  - cd electron
  - npm config set python python2.7
  - npm install
  - npm audit fix

build_script:
  - cd ..
  - sh build.sh

test: off

artifacts:
  - path: 'MTGATracker-win32-x64_*-SQUIRREL/RELEASES'
  - path: 'MTGATracker-win32-x64_*-SQUIRREL/*.nupkg'
  - path: 'MTGATracker-win32-x64_*-SQUIRREL/*.exe'

